spring:
  profiles:
    active: test
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dev
  cloud:
    config:
      server:
        git:
          uri: git@github.com:13716944414/microservicecloud-config.git #GitHub上面的git仓库名字
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-test
  cloud:
    config:
      server:
        git:
          uri: git@github.com:13716944414/microservicecloud-config.git #GitHub上面的git仓库名字